@startuml

' Copyright (C) 2014-2015  Thilo Fischer.
' Free for non-commercial and most commercial use. See LICENSE.txt for details.

note as N1
  This diagram does not depict the current
  implemention, but the planned rework of it.
end note

class Session {
  ' All the main_files of the translation units that make up the modules
  input_files() : File
}
note right: formally known as Environment
Logger "1" -- "1" Session : logger <
' From the Elements UML diagram
Element "1" <-- "0..1" Session : cursor <
Directory "0..n" <-- "0..n" Session : include_dirs <
Module "1..n" <-- "1" Session : modules <

class Options {
  + on_the_fly?()
  ' path to the cache directory, Session will create its cache from this
  + cache_dir()
  ' emulate a certain compilers command line argument processing (and possibly other behaviour)
  + compiler() : gcc, ...
  + language() : C, C++
  + dialect() : ANSI-C, C-99, ...
  - cmdline_options : Map
  - compiler
}
Session "1" --> "1" Options : options >
Compiler "0..1" <-- "0..n" Options : compiler (private) <

class Cache {
  + root_dir : String
}
' No cache only for on-the-fly invokations
Session "1" -- "0..1" Cache : cache >



class ParsingContext {

}
note right: formally known as Environment

class ContextBranch {
}
ParsingContext -- "1..n" ContextBranch

class PretokenizationContext {
}
ParsingContext "1" --> "1" PretokenizationContext : pretkn_context >
PhysicalLine "0..n" <-- ParsingContext : ongoing_line

class TokenizationContext {
  ' remaining charactres of current line to tokenize
  + remainder : String
}
ParsingContext "1" --> "1" TokenizationContext : tkn_context >
' most recently generated token, shold be 0 only at the very beginning of translation unit
Token "0..1" <-- ParsingContext : cursor
' Refers to a comment if the comment's beginning has already been parsed, but the comment's ending has not yet been found (e.g. block comments that span several lines)
Comment "0..1" <-- ParsingContext : ongoing_comment

class PreprocessingContext {
}
ParsingContext "1" --> "1" PreprocessingContext : pp_context >
' map from macro identifiers to their definitions
Macro "0..n" <-- PreprocessingContext : macros
' array of all preprocessing conditional branches chosen
PpDirCond "0..n" <-- PreprocessingContext : conditional_stack <
' most recent preprocessor line directive
PpDirLine "0..1" <-- PreprocessingContext : recent_line_directive <

class CompilationContext {
}
ParsingContext "1" --> "1" CompilationContext : cc_context >
' Which namespace, class, function, compound statement, etc. are we in at the current position in source code (formally known as expansion_stack)
Element "1..n" <-- CompilationContext : scope_stack <
' map from type identifiers to their definitions
Typedef "0..n" <-- CompilationContext : typedefs


@enduml