@startuml

[*] --> Normal
'Normal --> [*]

Normal --> Identifier : A-Za-z_
Identifier --> Identifier : A-Za-z0-9_
Identifier --> Identifier : . /NewToken+NewToken
'Normal --> Number : 0-9
Normal --> Number : 0-9.
Number --> Number : 0-9.A-Za-z
'Number --> Number : 0-9.A-Fa-fXxLlUu
'Number --> Number : 0-9
'Number --> NumberX : .
'Normal --> NumberX : .
'NumberX --> NumberX : 0-9
Normal --> Operator : +-*/%=!&|<>^
Operator --> Normal : = /NewToken
Operator --> Normal : whatever /Reject+NewToken
Operator --> Bitshift : <> [repeated]
Bitshift --> Normal : = /NewToken
Bitshift --> Normal : whatever /Reject+NewToken
'gibt es denn in C/C++ kein =~ ?
Normal --> Normal : ,:;?()[]{}~ /NewToken
Normal --> String : Doublequotes
String --> StringEscaped : \ 
StringEscaped --> String : whatever
String --> Normal : Doublequotes /NewToken

@enduml